### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by thunderstorm654** [OfficeDev/O365-Android-Microsoft-Graph-Connect#14]
The final prerequisite contains a broken link.

"A client id and redirect uri values of an application registered in Azure. This sample application must be granted the Send mail as a user permission for Microsoft Graph. Add a native client application in Azure and grant proper permissions to it."

The link to 'Add a native client application in Azure' is broken.

I found the instructions needed here: https://msdn.microsoft.com/office/office365/HowTo/add-common-consent-manually ('Register your native app with the Azure Management Portal' section then follow 'Specify the Office 365 API permissions your app requires' for the permissions).

**Comment by Ricalo** [comment]
Thank you, @thunderstorm654. I just updated the link :+1:

**Comment by iambmelt** [comment]
Hey @Ricalo - is this a change we'll need to move upstream to our other repos?

**Comment by Ricalo** [comment]
Yup, definitely.
